#!/usr/bin/php
<?php

require_once __DIR__ . "/commands/Controller/ControllerCommands.php";

const INPUT_ERROR = "Unknown Input";

$controllerCommands = new ControllerCommands();

$controllerType = readline("What Type of Controller? (t = twig; h = html)  ");

$controllerName = readline("Name of the Controller: ");


switch ($controllerType)
{
    case "t":   $controllerCommands->createTwigController($controllerName);
                break;

    case "h":   $controllerCommands->createHtmlController($controllerName);
                break;

    default:    echo INPUT_ERROR;
                die();
}

