#!/usr/bin/php
<?php

use Commands\errors\InOutException;
use Commands\TextHandler;
use Commands\UserInputOutput;
use Commands\UserInputParser;

require_once __DIR__.'/vendor/autoload.php';

$userInputOutput = new UserInputOutput();
$textHandler = new TextHandler();
$inputParser = new UserInputParser();

$texts = $textHandler->getTextsByLang();

try {
    if (isset($argv[1])) {
        $inputParser->parseUserInput($argv[1]);
    }
}catch (InOutException $ex)
{
    $userInputOutput->inputErrorHandling($ex);
}
